### ISSUE TITLE
Add markdown format readme.md

### ISSUE THREAD

**Issue by bcdady** [jdhitsolutions/MyMonitor#1]
I'd like to submit/publish a markdown readme.md format copy of about_mymonitor.help.txt.

Sample:
## KNOWN ISSUES

Occasionally, you may see a result like this:

```
Time        : 00:00:00.2095710
Application : {Google Chrome, Thunderbird}
WindowTitle : Hootsuite - Google Chrome Mozilla Thunderbird
Product     : {Google Chrome, Thunderbird}
```

**Comment by jdhitsolutions** [comment]
Sure. I tend to ignore those.

**Comment by jdhitsolutions** [comment]
I've added a README.md file.
